services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: tasks_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: